/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import UserInterface.Customer.OrderSolutionOfferJPanel;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    
    javax.swing.JPanel CardSequencePanel;
    Business business;
    CustomerProfile cp;
    
    public CustomerWorkAreaJPanel(Business b, JPanel clp, CustomerProfile cp) {
        
        business = b;
        this.CardSequencePanel = clp;
        this.cp = cp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOrderSolnOffer = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Customer Dashboard");

        btnOrderSolnOffer.setBackground(new java.awt.Color(102, 153, 255));
        btnOrderSolnOffer.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderSolnOffer.setText("Order Solution Offer");
        btnOrderSolnOffer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrderSolnOffer.setMaximumSize(new java.awt.Dimension(200, 40));
        btnOrderSolnOffer.setMinimumSize(new java.awt.Dimension(20, 23));
        btnOrderSolnOffer.setPreferredSize(new java.awt.Dimension(240, 30));
        btnOrderSolnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderSolnOfferIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnOrderHistory.setBackground(new java.awt.Color(102, 153, 255));
        btnOrderHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderHistory.setText("Order History");
        btnOrderHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrderHistory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnOrderHistory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnOrderHistory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(btnOrderSolnOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btnOrderSolnOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderSolnOfferIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderSolnOfferIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        OrderSolutionOfferJPanel oso = new OrderSolutionOfferJPanel(business, CardSequencePanel, cp);

        CardSequencePanel.add("OrderSolutionOffer", oso);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnOrderSolnOfferIdentifyResourceAssetsActionPerformed

    private void btnOrderHistoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderHistoryIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnOrderSolnOffer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
