/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.ChannelCatalog;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.MarketCatalog;
import TheBusiness.MarketModel.MarketChannelAssignment;
import TheBusiness.MarketModel.MarketChannelComboCatalog;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageTheBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;

    public ManageTheBusinessJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateMarketTable();
        populateChannelTable();
        populateComboTable();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarket = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChannel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMap = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCombo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 173, 96));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Pricentric");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 80, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage The Business");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 20, 1140, -1));

        tblMarket.setBackground(new java.awt.Color(0, 0, 0));
        tblMarket.setForeground(new java.awt.Color(255, 255, 255));
        tblMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Market Name", "Valid Channels"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMarket.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMarket);
        if (tblMarket.getColumnModel().getColumnCount() > 0) {
            tblMarket.getColumnModel().getColumn(0).setResizable(false);
            tblMarket.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblMarket.getColumnModel().getColumn(1).setResizable(false);
            tblMarket.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 270, 160));

        tblChannel.setBackground(new java.awt.Color(0, 0, 0));
        tblChannel.setForeground(new java.awt.Color(255, 255, 255));
        tblChannel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Channel type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChannel.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblChannel);
        if (tblChannel.getColumnModel().getColumnCount() > 0) {
            tblChannel.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, 160));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Market");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Market Channel Assignment");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 240, -1));

        btnMap.setBackground(new java.awt.Color(0, 0, 0));
        btnMap.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnMap.setForeground(new java.awt.Color(255, 255, 255));
        btnMap.setText("Map");
        btnMap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapLoginButtonActionPerformed(evt);
            }
        });
        add(btnMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 110, 30));

        tblCombo.setBackground(new java.awt.Color(0, 0, 0));
        tblCombo.setForeground(new java.awt.Color(255, 255, 255));
        tblCombo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Market", "Channel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCombo.setEnabled(false);
        tblCombo.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblCombo);
        if (tblCombo.getColumnModel().getColumnCount() > 0) {
            tblCombo.getColumnModel().getColumn(0).setResizable(false);
            tblCombo.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 160));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Channel");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void btnMapLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapLoginButtonActionPerformed
        // TODO add your handling code here:
 
        int selectedRow = tblMarket.getSelectedRow();
        int selectedRow1 = tblChannel.getSelectedRow();
 
       if (selectedRow < 0 || selectedRow1 < 0) {
                JOptionPane.showMessageDialog(null, "Please select a row from both market and channel tables to create combo assignment", "Warning", JOptionPane.WARNING_MESSAGE);
                //return;
             } 
             else
            {
            MarketCatalog marketCat = business.getMarketCatalog();
            ChannelCatalog channelCat = business.getChannelCatalog();
            String marketname=tblMarket.getValueAt(selectedRow, 0).toString();
            String channelname= tblChannel.getValueAt(selectedRow1, 0).toString();
            
            Market market=marketCat.findMarket(marketname);
            Channel channel=channelCat.findChannel(channelname);
            market.addValidChannel(channel);
            
            MarketChannelComboCatalog mccc = business.getMarketChannelComboCatalog();
            MarketChannelAssignment marketchannel = mccc.newMarketChannelCombo(market, channel);
            populateMarketTable();
            populateComboTable();

            //MapMarketChannel mc = business.getmapSupplierUserDirectory().addSupplierUser();
 
            
            
    }//GEN-LAST:event_btnMapLoginButtonActionPerformed

 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblChannel;
    private javax.swing.JTable tblCombo;
    private javax.swing.JTable tblMarket;
    // End of variables declaration//GEN-END:variables

    private void populateMarketTable() {
       DefaultTableModel dtm=(DefaultTableModel)tblMarket.getModel();
        dtm.setRowCount(0);
        
        for(Market market: business.getMarketCatalog().getMarkets())
        {
           Object[] row=new Object[4];
           row[0]=market.getName();
           row[1]=market.getValidchannels();
        
           
          dtm.addRow(row);
        }  
    }

    private void populateChannelTable() {
       DefaultTableModel dtm=(DefaultTableModel)tblChannel.getModel();
        dtm.setRowCount(0);
        
        for(Channel channel: business.getChannelCatalog().getChannellist())
        {
           Object[] row=new Object[4];
           row[0]=channel.getChannelType();
           
        
           
          dtm.addRow(row);
        }  
    }

    private void populateComboTable() {
        
        DefaultTableModel dtm=(DefaultTableModel)tblCombo.getModel();
        dtm.setRowCount(0);
        
        for(MarketChannelAssignment mca: business.getMarketChannelComboCatalog().getMcalist())
        {
           Object[] row=new Object[2];
           row[0]=mca.getMarket();
           row[1]=mca.getChannel();
                  
           
        
           
          dtm.addRow(row);
        } 
        
    }

}
