/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Marketing;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.SolutionOffer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malin
 */
public class ViewSolutionCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSolutionCatalog
     */
    JPanel CardSequencePanel;
    Business business;
    public ViewSolutionCatalogJPanel(Business bz, JPanel jp) {
        
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateSolutionCatalogTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolCat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        tblSolCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Market ", "Channel", "Products", "Floor price", "Ceil price", "Target price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolCat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSolCat);
        if (tblSolCat.getColumnModel().getColumnCount() > 0) {
            tblSolCat.getColumnModel().getColumn(0).setResizable(false);
            tblSolCat.getColumnModel().getColumn(0).setPreferredWidth(250);
            tblSolCat.getColumnModel().getColumn(1).setResizable(false);
            tblSolCat.getColumnModel().getColumn(1).setPreferredWidth(180);
            tblSolCat.getColumnModel().getColumn(2).setResizable(false);
            tblSolCat.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblSolCat.getColumnModel().getColumn(3).setResizable(false);
            tblSolCat.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblSolCat.getColumnModel().getColumn(4).setResizable(false);
            tblSolCat.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblSolCat.getColumnModel().getColumn(5).setResizable(false);
            tblSolCat.getColumnModel().getColumn(5).setPreferredWidth(250);
        }

        jLabel1.setText("SolutionCatalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolCat;
    // End of variables declaration//GEN-END:variables

    private void populateSolutionCatalogTable() {
        
         DefaultTableModel dtm=(DefaultTableModel)tblSolCat.getModel();
        dtm.setRowCount(0);
        
        for(SolutionOffer so: business.getSolutionOfferCatalog().getSolutionoffers())
        {
           Object[] row=new Object[6];
           row[0]=so.getMarketchannelcomb().getMarket();
           row[1]=so.getMarketchannelcomb().getChannel();
           row[2]=so.getProducts();
           row[3]=so.getFp();
           row[4]=so.getCp();
           row[5]=so.getTp();
           
            dtm.addRow(row);
        } 
    }
}
