/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Marketing;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.SolutionOffer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malin
 */
public class ViewSolutionCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSolutionCatalog
     */
    JPanel CardSequencePanel;
    Business business;
    public ViewSolutionCatalogJPanel(Business bz, JPanel jp) {
        
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateSolutionCatalogTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolCat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 173, 96));

        tblSolCat.setBackground(new java.awt.Color(0, 0, 0));
        tblSolCat.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblSolCat.setForeground(new java.awt.Color(255, 255, 255));
        tblSolCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Market ", "Channel", "Products", "Floor price", "Ceil price", "Target price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolCat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSolCat);
        if (tblSolCat.getColumnModel().getColumnCount() > 0) {
            tblSolCat.getColumnModel().getColumn(0).setResizable(false);
            tblSolCat.getColumnModel().getColumn(0).setPreferredWidth(250);
            tblSolCat.getColumnModel().getColumn(1).setResizable(false);
            tblSolCat.getColumnModel().getColumn(1).setPreferredWidth(180);
            tblSolCat.getColumnModel().getColumn(2).setResizable(false);
            tblSolCat.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblSolCat.getColumnModel().getColumn(3).setResizable(false);
            tblSolCat.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblSolCat.getColumnModel().getColumn(4).setResizable(false);
            tblSolCat.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblSolCat.getColumnModel().getColumn(5).setResizable(false);
            tblSolCat.getColumnModel().getColumn(5).setPreferredWidth(250);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Solution Catalog");

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Back)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolCat;
    // End of variables declaration//GEN-END:variables

    private void populateSolutionCatalogTable() {
        
         DefaultTableModel dtm=(DefaultTableModel)tblSolCat.getModel();
        dtm.setRowCount(0);
        
        for(SolutionOffer so: business.getSolutionOfferCatalog().getSolutionoffers())
        {
           Object[] row=new Object[6];
           row[0]=so.getMarketchannelcomb().getMarket();
           row[1]=so.getMarketchannelcomb().getChannel();
           row[2]=so.getProducts();
           row[3]=so.getFp();
           row[4]=so.getCp();
           row[5]=so.getTp();
           
            dtm.addRow(row);
        } 
    }
}
