/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import MarketAnalytics.AnalysisHelper;
import TheBusiness.Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ReportMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportMenuJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    AnalysisHelper analysishelper;
    public ReportMenuJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        this.analysishelper = new AnalysisHelper(this.business);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRep1 = new javax.swing.JButton();
        btnRep5 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 173, 96));

        btnRep1.setBackground(new java.awt.Color(0, 0, 0));
        btnRep1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRep1.setForeground(new java.awt.Color(255, 255, 255));
        btnRep1.setText("Top 3 best negotiated solutions by market");
        btnRep1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep1.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep1.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep1.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep5.setBackground(new java.awt.Color(0, 0, 0));
        btnRep5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRep5.setForeground(new java.awt.Color(255, 255, 255));
        btnRep5.setText("Analysis of pricing strategy");
        btnRep5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep5.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep5.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep5.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep5IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep3.setBackground(new java.awt.Color(0, 0, 0));
        btnRep3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRep3.setForeground(new java.awt.Color(255, 255, 255));
        btnRep3.setText("Top 3 best sales persons");
        btnRep3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep3.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep3.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep3.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep2.setBackground(new java.awt.Color(0, 0, 0));
        btnRep2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRep2.setForeground(new java.awt.Color(255, 255, 255));
        btnRep2.setText("Top 3 best customers");
        btnRep2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep2.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep2.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep2.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep4.setBackground(new java.awt.Color(0, 0, 0));
        btnRep4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnRep4.setForeground(new java.awt.Color(255, 255, 255));
        btnRep4.setText("Total marginal revenue by market");
        btnRep4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep4.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep4.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep4.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Performance Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnRep5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopNegotiatedSolutions();
    }//GEN-LAST:event_btnRep1IdentifyResourceAssetsActionPerformed

    private void btnRep5IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep5IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.analyzePricing();
    }//GEN-LAST:event_btnRep5IdentifyResourceAssetsActionPerformed

    private void btnRep3IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopSalespeople();
    }//GEN-LAST:event_btnRep3IdentifyResourceAssetsActionPerformed

    private void btnRep2IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopCustomers();
    }//GEN-LAST:event_btnRep2IdentifyResourceAssetsActionPerformed

    private void btnRep4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTotalMarginalRevenueByMarket();
    }//GEN-LAST:event_btnRep4IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnRep5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
