/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import MarketAnalytics.AnalysisHelper;
import TheBusiness.Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ReportMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportMenuJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    AnalysisHelper analysishelper;
    public ReportMenuJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        this.analysishelper = new AnalysisHelper(this.business);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRep1 = new javax.swing.JButton();
        btnRep5 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnRep1.setBackground(new java.awt.Color(102, 153, 255));
        btnRep1.setForeground(new java.awt.Color(255, 255, 255));
        btnRep1.setText("Top 3 best negotiated solutions by market");
        btnRep1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep1.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep1.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep1.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep5.setBackground(new java.awt.Color(102, 153, 255));
        btnRep5.setForeground(new java.awt.Color(255, 255, 255));
        btnRep5.setText("Analysis of pricing strategy");
        btnRep5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep5.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep5.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep5.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep5IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep3.setBackground(new java.awt.Color(102, 153, 255));
        btnRep3.setForeground(new java.awt.Color(255, 255, 255));
        btnRep3.setText("Top 3 best sales persons");
        btnRep3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep3.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep3.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep3.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep2.setBackground(new java.awt.Color(102, 153, 255));
        btnRep2.setForeground(new java.awt.Color(255, 255, 255));
        btnRep2.setText("Top 3 best customers");
        btnRep2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep2.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep2.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep2.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRep4.setBackground(new java.awt.Color(102, 153, 255));
        btnRep4.setForeground(new java.awt.Color(255, 255, 255));
        btnRep4.setText("Total marginal revenue by market");
        btnRep4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRep4.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRep4.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRep4.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnRep5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRep5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopNegotiatedSolutions();
    }//GEN-LAST:event_btnRep1IdentifyResourceAssetsActionPerformed

    private void btnRep5IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep5IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.analyzePricing();
    }//GEN-LAST:event_btnRep5IdentifyResourceAssetsActionPerformed

    private void btnRep3IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopSalespeople();
    }//GEN-LAST:event_btnRep3IdentifyResourceAssetsActionPerformed

    private void btnRep2IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTopCustomers();
    }//GEN-LAST:event_btnRep2IdentifyResourceAssetsActionPerformed

    private void btnRep4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        analysishelper.printTotalMarginalRevenueByMarket();
    }//GEN-LAST:event_btnRep4IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnRep5;
    // End of variables declaration//GEN-END:variables
}
